### ISSUE TITLE
Dune Developer Preview (Sept-28-2024) fails to build z3

### ISSUE THREAD

**Issue by cogumbreiro** [ocaml/dune#10970]
## Expected Behavior

I would like to migrate my project to Dune developer preview.

## Actual Behavior

`dune build` is unable to compile the package `z3`. See point 4 below for output. 

## Reproduction

<details>

<summary>1. Create a new project</summary>

```
$ dune init proj hello_world
$ cd hello_world
```

</details>

<details>

<summary>
2. Change the dependency section of `dune-project` and add `z3`.
</summary>

```
 (depends ocaml dune
   (z3 (>= 4.13.0)) 
 )
```
</details>

<details>
<summary>
3. Update `bin/dune` to include `z3` in the libraries section
</summary>

```
(executable
 (public_name hello_world)
 (name main)
 (libraries hello_world z3))
```
</details>

<details>
<summary>
4. `dune build` fails in a Python script.
</summary>

```
$ dune build
    Building z3.4.13.0-3            
File "dune.lock/z3.pkg", line 11, characters 7-14:
11 |   (run python3 scripts/mk_make.py --ml)
            ^^^^^^^
Error: Logs for package z3
Traceback (most recent call last):
  File "/home/tiago/Work/hello_world/_build/.sandbox/f902b8116518b10f30ed7475b3b5c86b/_private/default/.pkg/z3/source/scripts/mk_make.py", line 21, in <module>
    mk_makefile()
  File "/home/tiago/Work/hello_world/_build/.sandbox/f902b8116518b10f30ed7475b3b5c86b/_private/default/.pkg/z3/source/scripts/mk_util.py", line 2809, in mk_makefile
    mk_install(out)
  File "/home/tiago/Work/hello_world/_build/.sandbox/f902b8116518b10f30ed7475b3b5c86b/_private/default/.pkg/z3/source/scripts/mk_util.py", line 2764, in mk_install
    c.mk_install(out)
  File "/home/tiago/Work/hello_world/_build/.sandbox/f902b8116518b10f30ed7475b3b5c86b/_private/default/.pkg/z3/source/scripts/mk_util.py", line 2121, in mk_install
    self._init_ocamlfind_paths()
  File "/home/tiago/Work/hello_world/_build/.sandbox/f902b8116518b10f30ed7475b3b5c86b/_private/default/.pkg/z3/source/scripts/mk_util.py", line 1980, in _init_ocamlfind_paths
    raise MKException('The destdir reported by {ocamlfind} ({destdir}) does not exist'.format(ocamlfind=OCAMLFIND, destdir=self.destdir))
mk_exception.MKException: 'The destdir reported by ocamlfind (/home/tiago/Work/hello_world/_build/.sandbox/f902b8116518b10f30ed7475b3b5c86b/_private/default/.pkg/z3/target/lib) does not exist'
```

</details>

## Specifications

```
$ dune --version
"Dune Developer Preview: build 2024-09-28T01:30:13+00:00, git revision
17071ec30d10390badcb6cb1f6a43984b1be54a6"
$ ocaml --version
The OCaml toplevel, version 5.2.0
$ cat /etc/issue
Pop!_OS 22.04 LTS \n \l
```

**Comment by Leonidas-from-XIV** [comment]
This looks like an issue where our ocamlfind fork reports a `DESTDIR` that doesn't exist. I am not sure whether the right way would be to patch `ocamlfind` to create it when reporting it or whether Z3 should `mkdir $DESTDIR`.

**Comment by rgrinberg** [comment]
Reporting it on creation sounds reasonable. If you patch z3, you might have to patch other packages that rely on this as well.

**Comment by cogumbreiro** [comment]
Closing this issue, as z3 now builds fine in the current build!
```
"Dune Developer Preview: build 2025-05-11T02:42:32Z, git revision
aaa7e952cd67aebc33d3d9472c193ca53fbae120"
```

**Comment by cogumbreiro** [comment]
I was trying to reproduce the success above, but it turns out that I had missed the `dune pkg lock` command and `dune b` was just picking up the global switch.

That is to say, that z3 actually doesn't work.

```
$ dune --version
"Dune Developer Preview: build 2025-07-14T02:58:13Z, git revision
36b11f2eaea1df8c96afdbe2c15758d5bf6eca67"
$ dune pkg lock
Solution for dune.lock:                                              
- arch-x86_64.1
- conf-c++.1.0
- conf-gmp.5
- conf-mingw-w64-g++-i686.1
- conf-mingw-w64-g++-x86_64.1
- conf-mingw-w64-gcc-i686.1
- conf-mingw-w64-gcc-x86_64.1
- conf-mingw-w64-gmp-i686.1
- conf-mingw-w64-gmp-x86_64.1
- conf-pkg-config.4
- conf-python-3.9.0.0
- flexdll.0.44
- host-arch-x86_32.1
- host-arch-x86_64.1
- ocaml.5.3.0
- ocaml-base-compiler.5.3.0
- ocaml-compiler.5.3.0
- ocaml-config.3
- ocaml-env-mingw32.1
- ocaml-env-mingw64.1
- ocamlfind.1.9.8+dune
- system-mingw.1
- z3.4.15.2
- zarith.1.14
$ dune b
    Building ocaml-compiler.5.3.0
    Building ocaml-base-compiler.5.3.0
    Building conf-pkg-config.4      
    Building conf-c++.1.0           
    Building conf-gmp.5             
    Building conf-python-3.9.0.0    
    Building ocaml-config.3         
    Building ocaml.5.3.0            
    Building ocamlfind.1.9.8+dune   
    Building zarith.1.14           
    Building z3.4.15.2             
File "dune.lock/z3.4.15.2.pkg", line 29, characters 12-19:
29 |        (run python3 scripts/mk_make.py --ml))
                 ^^^^^^^
Error: Logs for package z3
Traceback (most recent call last):
  File "/home/tiago/Work/hello_world2/_build/.sandbox/3325f98e39b4179b80048b75ae956f03/_private/default/.pkg/z3/source/scripts/mk_make.py", line 21, in <module>
    mk_makefile()
  File "/home/tiago/Work/hello_world2/_build/.sandbox/3325f98e39b4179b80048b75ae956f03/_private/default/.pkg/z3/source/scripts/mk_util.py", line 2814, in mk_makefile
    mk_install(out)
  File "/home/tiago/Work/hello_world2/_build/.sandbox/3325f98e39b4179b80048b75ae956f03/_private/default/.pkg/z3/source/scripts/mk_util.py", line 2769, in mk_install
    c.mk_install(out)
  File "/home/tiago/Work/hello_world2/_build/.sandbox/3325f98e39b4179b80048b75ae956f03/_private/default/.pkg/z3/source/scripts/mk_util.py", line 2124, in mk_install
    self._init_ocamlfind_paths()
  File "/home/tiago/Work/hello_world2/_build/.sandbox/3325f98e39b4179b80048b75ae956f03/_private/default/.pkg/z3/source/scripts/mk_util.py", line 1980, in _init_ocamlfind_paths
    raise MKException('The destdir reported by {ocamlfind} ({destdir}) does not exist'.format(ocamlfind=OCAMLFIND, destdir=self.destdir))
mk_exception.MKException: 'The destdir reported by ocamlfind (/home/tiago/Work/hello_world2/_build/.sandbox/3325f98e39b4179b80048b75ae956f03/_private/default/.pkg/z3/target/lib) does not exist'
```

**Comment by cogumbreiro** [comment]
I manage to advance a bit further, by editing `dune.lock/z3.4.15.2.pkg` and changing the line that said:
```
(run python3 scripts/mk_make.py --ml)
```
to say
```
(system python3 scripts/mk_make.py --ml)
```
building z3 eventually failed with a linking error ([full log attached](https://github.com/user-attachments/files/21222038/log.txt))
```
z3native_stubs.c:(.text+0x49d29): undefined reference to `Z3_rcf_num_sign_condition_coefficients'
/usr/bin/ld: ../_private/default/.pkg/z3/target/lib/z3/libz3ml.a(z3native_stubs.o): in function `n_rcf_sign_condition_coefficient':
z3native_stubs.c:(.text+0x49ec3): undefined reference to `Z3_rcf_sign_condition_coefficient'
/usr/bin/ld: ../_private/default/.pkg/z3/target/lib/z3/libz3ml.a(z3native_stubs.o): in function `n_optimize_set_initial_value':
z3native_stubs.c:(.text+0x4d944): undefined reference to `Z3_optimize_set_initial_value'
/usr/bin/ld: ../_private/default/.pkg/z3/target/lib/z3/libz3ml.a(z3native_stubs.o): in function `n_qe_model_project_with_witness':
z3native_stubs.c:(.text+0x58bad): undefined reference to `Z3_qe_model_project_with_witness'
collect2: error: ld returned 1 exit status
```
**Attachments:**
- [log.txt](https://github.com/user-attachments/files/21222038/log.txt)

**Comment by Leonidas-from-XIV** [comment]
Yes, the problem is that findlib reports a path that will not be valid after the build has finished (as dune package management will move the build artifacts elsewhere and remove the build directory). I believe @dra27 was working on making that bit of findlib relocatable too, but no idea about the current state of it.

**Comment by Alizter** [comment]
I think this is another symptom of https://github.com/ocaml/dune/issues/10294

**Comment by wintersteiger** [comment]
Same here. I managed to get through the build by adding ```(run sh -c "mkdir -p `ocamlfind printconf destdir`")``` in the `.pkg` file, but then I get undefined references too. I think it is indeed quite likely that #10294 is related; if the env vars aren't set up correctly it won't find the library when it needs it.

**Comment by Alizter** [comment]
I'm planning to make some substantial changes to how the package management rules will work. It's likely that #10294 will be directly addressable as a result of this. I'll keep z3 in mind when testing.
